### ISSUE TITLE
failed to create cluster: failed to init node with kubeadm

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#2248]
```
 kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✗ Starting control-plane 🕹️ 
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 2
Command Output: SIGSEGV: segmentation violation
PC=0x37 m=0 sigcode=0

goroutine 1 [running]:
runtime: unknown pc 0x37
stack: frame={sp:0xc000702085, fp:0x0} stack=[0xc0002e6000,0xc0002ee000)

runtime: unknown pc 0x37
stack: frame={sp:0xc000702085, fp:0x0} stack=[0xc0002e6000,0xc0002ee000)


goroutine 4 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2972660)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

rax    0x0
rbx    0x0
rcx    0x0
rdx    0x0
rdi    0x0
rsi    0x0
rbp    0x0
rsp    0xc000702085
r8     0xc000693960
r9     0x0
r10    0x1
r11    0x0
r12    0x0
r13    0x37
r14    0x0
r15    0x0
rip    0x37
rflags 0xdd7b
cs     0x38
fs     0x0
gs     0x0
```

```
Mac mini (M1, 2020)
Apple M1
8 GB
```

```
kind version
kind v0.10.0 go1.16beta1 darwin/arm64

```

```
 docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: KVLR:23EP:YXTU:H7RZ:7LTK:2755:XTMC:JALW:PLL5:JPKF:QV5X:PYGN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

**Comment by BenTheElder** [comment]
v0.10.0 does not support macOS/arm, nor does that image. Please see #166
