### ISSUE TITLE
getSubnets failed  podman with kind 0.14.0 and podman 4.1.1

### ISSUE THREAD

**Issue by zhangzewen** [kubernetes-sigs/kind#2887]
**What happened**:
**Can not create k8s cluster with  podman**
```shell
KIND_EXPERIMENTAL_PROVIDER=podman  kind create cluster --config ./manifests/kind/kind.cluster.yaml --verbosity 10
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "kind" ...
DEBUG: podman/images.go:58] Image: docker.io/kindest/node:v1.21.1 present locally
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼 
 ✓ Preparing nodes 📦  
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
sigs.k8s.io/kind/pkg/cluster/internal/providers/podman.getSubnets({0x781f17?, 0x7aa7d0?})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/internal/providers/podman/provision.go:275 +0x199
sigs.k8s.io/kind/pkg/cluster/internal/providers/podman.getProxyEnv(0x782028?, {0x781f17, 0x4})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/internal/providers/podman/provision.go:249 +0x74
sigs.k8s.io/kind/pkg/cluster/internal/providers/podman.commonArgs(0xc00013f600, {0x781f17, 0x4})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/internal/providers/podman/provision.go:137 +0x2c5
sigs.k8s.io/kind/pkg/cluster/internal/providers/podman.planCreation(0xc00013f600, {0x781f17, 0x4})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/internal/providers/podman/provision.go:40 +0x78
sigs.k8s.io/kind/pkg/cluster/internal/providers/podman.(*provider).Provision(0xc0001322e8, 0xc0002f8000, 0xc00013f600)
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/internal/providers/podman/provider.go:94 +0x1f0
sigs.k8s.io/kind/pkg/cluster/internal/create.Cluster({0x806ee8, 0xc00011f350?}, {0x807bd0?, 0xc0001322e8}, 0xc000154730)
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/internal/create/create.go:101 +0x36c
sigs.k8s.io/kind/pkg/cluster.(*Provider).Create(0xc0001566c0, {0x0, 0x0}, {0xc000163be0, 0x7, 0xc000103d01?})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cluster/provider.go:182 +0xa5
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.runE({0x806ee8?, 0xc00011f350}, {{0x803f60, 0xc000124000}, {0x803fa0, 0xc000124008}, {0x803fa0, 0xc000124010}}, 0xc000154410)
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cmd/kind/create/cluster/createcluster.go:80 +0x408
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.NewCommand.func1(0xc000211400?, {0xc000158900?, 0x4?, 0x4?})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/pkg/cmd/kind/create/cluster/createcluster.go:55 +0x72
github.com/spf13/cobra.(*Command).execute(0xc000211400, {0xc0001588c0, 0x4, 0x4})
	/home/zewen/GoWorkspace/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000210000)
	/home/zewen/GoWorkspace/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/zewen/GoWorkspace/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
sigs.k8s.io/kind/cmd/kind/app.Run({0x806ee8, 0xc00011f350}, {{0x803f60, 0xc000124000}, {0x803fa0, 0xc000124008}, {0x803fa0, 0xc000124010}}, {0xc000128010, 0x6, ...})
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/cmd/kind/app/main.go:53 +0x145
sigs.k8s.io/kind/cmd/kind/app.Main()
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/cmd/kind/app/main.go:35 +0xe7
main.main()
	/home/zewen/GoWorkspace/pkg/mod/sigs.k8s.io/kind@v0.14.0/main.go:25 +0x17
make: *** [Makefile.podman:5: cluster] Error 2

```
**What you expected to happen**:
can create k8s cluster with provider
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```shell
➜  k8sdev git:(master) ✗ podman network inspect  kind 
[
     {
          "name": "kind",
          "id": "0b27c158feb36ab18a10ff687909ec730ece6280581dd407e2672359be7725dd",
          "driver": "bridge",
          "network_interface": "cni-podman1",
          "created": "2022-08-18T07:44:24.82842875+08:00",
          "subnets": [
               {
                    "subnet": "fc00:f853:ccd:e793::/64",
                    "gateway": "fc00:f853:ccd:e793::1"
               },
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
```
**Environment:**

```shell
➜  k8sdev git:(master) ✗ podman version        
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Sat Jul 23 03:05:59 2022
OS/Arch:      linux/amd64
➜  k8sdev git:(master) ✗ kind version
kind v0.14.0 go1.18.3 linux/amd64
```

**Comment by BenTheElder** [comment]
/triage duplicate
we just patched this, if you clone the repo and do `make build` a binary with the fix will be in `bin/kind`.

we hope to cut a kind release next week alongside k8s 1.25

the previous issue and discussion is https://github.com/kubernetes-sigs/kind/issues/2882
