### ISSUE TITLE
Documentation: Using ingress not working as expected (ingress-nginx)

### ISSUE THREAD

**Issue by carslen** [kubernetes-sigs/kind#3024]
**What happened**:
Following the documentation [Using Ingress](https://kind.sigs.k8s.io/docs/user/ingress/) I'm unable to get the example pods working:

```shell
$ k get pods
NAME      READY   STATUS             RESTARTS        AGE
bar-app   0/1     CrashLoopBackOff   6 (5m ago)      10m
foo-app   0/1     CrashLoopBackOff   6 (4m56s ago)   10m
``` 

**What you expected to happen**:
Two running containers responding to curl, but instead only the ingress controller reponds with:

```
$ curl localhost/foo
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
On the other hand this indicates, that the ingress is working, acknowledged by:

```shell
$ k -n ingress-nginx get all
NAME                                           READY   STATUS      RESTARTS   AGE
pod/ingress-nginx-admission-create-hpffg       0/1     Completed   0          39m
pod/ingress-nginx-admission-patch-zvsz8        0/1     Completed   0          39m
pod/ingress-nginx-controller-6bccc5966-g4l64   1/1     Running     0          39m

NAME                                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/ingress-nginx-controller             NodePort    10.96.118.204   <none>        80:31073/TCP,443:30516/TCP   39m
service/ingress-nginx-controller-admission   ClusterIP   10.96.118.7     <none>        443/TCP                      39m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   1/1     1            1           39m

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-6bccc5966   1         1         1       39m

NAME                                       COMPLETIONS   DURATION   AGE
job.batch/ingress-nginx-admission-create   1/1           6s         39m
job.batch/ingress-nginx-admission-patch    1/1           6s         39m
```
**How to reproduce it (as minimally and precisely as possible)**:
Follow the  ingress documentation for ingress-nginx. Error appears after applying `usage.yaml`. Additional informations will follow in comments to this bug report.

**Anything else we need to know?**:
#2927 mentioned the same issue, but issue was closed. So I open the bug report as requested in closed issue.

**Environment:**

- kind version: (use `kind version`): `kind v0.17.0 go1.19.2 darwin/arm64`
- Kubernetes version: (use `kubectl version`): 
  ```
  Client Version: v1.25.4
  Kustomize Version: v4.5.7
  Server Version: v1.25.3
  ```
- Docker version: (use `docker info`):
  ```shell
  $ colima version
  colima version 0.4.6
  git commit: 10377f3a20c2b0f7196ad5944264b69f048a3d40

  runtime: docker
  arch: aarch64
  client: v20.10.21
  server: v20.10.11
  ```
- OS (e.g. from `/etc/os-release`):
  ```
  $ sw_vers
  ProductName:	macOS
  ProductVersion:	12.6
  BuildVersion:	21G115
  ```

**Comment by carslen** [comment]
```shell
$ k logs pods/foo-app
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x6955a0, 0x9)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc420026000, 0xc420036000)
	/usr/local/go/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0x6a4348, 0x0)
	/usr/local/go/src/runtime/proc.go:1628 +0x137
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x7cc200)
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc420022788 sp=0xc420022780
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227e0 sp=0xc420022788
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200227e8 sp=0xc4200227e0
```
Same for _bar-app_.

**Comment by BenTheElder** [comment]
What architecture is the Lima VM emulating? Is it also running qemu-userspace?
I think this is a problem with the host environment and the images with running cross-architecture, see: https://github.com/docker/for-mac/issues/6137

**Comment by BenTheElder** [comment]
We should check for a newer HTTP echo image or switch to agnhost. I think we had the same problem in the Kubernetes.io docs and switched to agnhost.

**Comment by BenTheElder** [comment]
Yes, we did have this same issue https://github.com/kubernetes/website/pull/37383

**Comment by BenTheElder** [comment]
thank you @carslen !
