### ISSUE TITLE
Kind, DinD, and bind mounts

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/kind#387]
Please note for the purposes of this issue, assume that all commands are executed from a local clone of https://github.com/kubernetes/cloud-provider-vsphere.

I'm trying to figure out how to make Kind's `extraMounts` feature work when running in Docker-in-Docker (DinD). The following works:

```
# Launch an image and interact with its shell
$ docker run -it --rm \
  -e "PROJECT_ROOT=$(pwd)" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$(pwd)":/go/src/k8s.io/cloud-provider-vsphere \
  gcr.io/cloud-provider-vsphere/ci:1e34afa6

# Launch a second image using DinD, mapping a file from the host system into the second image.
$ docker run -it --rm \
  -v "${PROJECT_ROOT}/test/kind/c01-product-serial.txt":/sys/class/dmi/id/product_serial:ro \
  debian:stretch \
  cat /sys/class/dmi/id/product_serial && echo
VMware-fe 19 f4 04 88 86 66 40-a1 6d cb c4 19 3d 5b 93
```

However, when I try to launch Kind from inside the first container I receive the following error:
```
$ docker run -it --rm \
>   -e "PROJECT_ROOT=$(pwd)" \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -v "$(pwd)":/go/src/k8s.io/cloud-provider-vsphere \
>   gcr.io/cloud-provider-vsphere/ci \
>   make integration-test
Makefile:27: This project uses Go modules and should not be cloned into the GOPATH
make -C test/integration
make[1]: Entering directory '/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make build-ccm-image
make[2]: Entering directory '/go/src/k8s.io/cloud-provider-vsphere/test/integration'
GOOS=linux make -C ../.. build-ccm-image
make[3]: Entering directory '/go/src/k8s.io/cloud-provider-vsphere'
make[3]: Nothing to be done for 'build-ccm-image'.
make[3]: Leaving directory '/go/src/k8s.io/cloud-provider-vsphere'
make[2]: Leaving directory '/go/src/k8s.io/cloud-provider-vsphere/test/integration'
make cluster-up
make[2]: Entering directory '/go/src/k8s.io/cloud-provider-vsphere/test/integration'
kind create cluster --config "kind-config.yaml" --name "ccm-integration-test"
Creating cluster "ccm-integration-test" ...
 ✓ Ensuring node image (kindest/node:v1.13.3) 🖼
ERRO[19:16:12] 73ddc2bfebbfff1ce8b620ab20af341d041c8cc2c5ff9a9d0f3a3288d26788cb 
ERRO[19:16:12] docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/kind/w01-product-serial.txt\\\" to rootfs \\\"/var/lib/docker/overlay2/6e653b30afcde1732e06e9fd41ef36f3685206aab9dae4a603014417aaf1e8f4/merged\\\" at \\\"/var/lib/docker/overlay2/6e653b30afcde1732e06e9fd41ef36f3685206aab9dae4a603014417aaf1e8f4/merged/sys/devices/virtual/dmi/id/product_serial\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type. 
 ✗ Preparing nodes 📦📦
ERRO[19:16:12] docker run error: exit status 125            
ERRO[19:16:12] 9773663b0449de0cf73c185d6d139e2220c4f382caab36bb5d7dc21cbacf7694 
ERRO[19:16:12] docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/kind/c01-product-serial.txt\\\" to rootfs \\\"/var/lib/docker/overlay2/b651456d8b1324fef134558a34ad9772a01067d713fa1d5105679728284660cc/merged\\\" at \\\"/var/lib/docker/overlay2/b651456d8b1324fef134558a34ad9772a01067d713fa1d5105679728284660cc/merged/sys/devices/virtual/dmi/id/product_serial\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type. 
panic: send on closed channel

goroutine 37 [running]:
sigs.k8s.io/kind/pkg/cluster/internal/create.createNodeContainers.func1(0xc000100410, 0xc00031c0f0, 0x2d, 0xc0002520c0, 0xc0000885a0)
	/go/src/sigs.k8s.io/kind/pkg/cluster/internal/create/nodes.go:109 +0x116
created by sigs.k8s.io/kind/pkg/cluster/internal/create.createNodeContainers
	/go/src/sigs.k8s.io/kind/pkg/cluster/internal/create/nodes.go:105 +0x33a
Makefile:16: recipe for target 'cluster-up' failed
make[2]: *** [cluster-up] Error 2
make[2]: Leaving directory '/go/src/k8s.io/cloud-provider-vsphere/test/integration'
Makefile:71: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/go/src/k8s.io/cloud-provider-vsphere/test/integration'
Makefile:265: recipe for target 'integration-test' failed
make: *** [integration-test] Error 2
```

I'm not sure what Kind is doing, but bind mounting an object when using DinD works as long as the object's local host path is provided. Except it's not working in Kind.

**Comment by akutz** [comment]
Wow. So I just ran `make integration-test` locally and it failed with the same. It used to work. I wonder if trying to get it working with DinD borked something, because this gets **real** weird:

```
$ stat /Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/kind/c01-product-serial.txt
  File: /Users/akutz/Projects/go/src/k8s.io/cloud-provider-vsphere/test/kind/c01-product-serial.txt
  Size: 64        	Blocks: 0          IO Block: 4194304 directory
Device: 1000004h/16777220d	Inode: 8612033825  Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  503/   akutz)   Gid: (   20/   staff)
Access: 2019-03-18 14:23:58.397279357 -0500
Modify: 2019-03-18 13:18:48.013737512 -0500
Change: 2019-03-18 13:18:48.013737512 -0500
 Birth: 2019-03-18 13:18:48.013737512 -0500
```

A directory? And yet...

**Comment by akutz** [comment]
Okay, I seem to have had some look by removing the `type: File` in the `kind-config.yaml`. I'm going to try this in a fresh environment and if it works I'll close the issue.

**Comment by akutz** [comment]
I’m closing the issue. Once again it was an ID-10-T error. I originally gave it the wrong local host path, and so it created directories for the missing files, and then subsequent attempts just used the same path and gave the error.

My fault for having the same project cloned twice on my local host. I had moved it out of the GOPATH and neglected to remove the original copy.
