### ISSUE TITLE
WSL2: Issues with iptables rules

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes-sigs/kind#720]
**What happened**:

I was digging more into the kindnet logs to figure out what was going on, and it looks like WSL2 doesn't set up some of the expected iptables chains. This needs either a change in WSL2 or a workaround to create them in `kind`.

/tmp/749344725/kind-control-plane/containers/kindnet-t8x85_kube-system_kindnet-cni-c6987900ab828ff099f10415c4576751aae5eba577918446672c4f21455a7b8c.log

```
2019-07-18T18:32:17.035941Z stdout F hostIP = 172.17.0.2
2019-07-18T18:32:17.0360292Z stdout F podIP = 172.17.0.2
2019-07-18T18:32:18.1656212Z stderr F panic: failed to ensure that nat chain KIND-MASQ-AGENT jumps to MASQUERADE: error appending rule: exit status 1: iptables: No chain/target/match by that name.
2019-07-18T18:32:18.1657112Z stderr F 
2019-07-18T18:32:18.1657504Z stderr F 
2019-07-18T18:32:18.1657757Z stderr F goroutine 9 [running]:
2019-07-18T18:32:18.1657945Z stderr F main.main.func1(0xc0001e7440)
2019-07-18T18:32:18.1658146Z stderr F 	/src/main.go:76 +0x67
2019-07-18T18:32:18.1658333Z stderr F created by main.main
2019-07-18T18:32:18.1658489Z stderr F 	/src/main.go:73 +0x318
```

/tmp/749344725/kind-control-plane/containers/kube-proxy-np49z_kube-system_kube-proxy-bd3bd98712ca9163e26d2ce8671dcfb66696aef8abd96aa0f937476048307e30.log

```
2019-07-18T18:32:19.6952255Z stderr F E0718 18:32:19.693704       1 proxier.go:714] Failed to ensure that filter chain INPUT jumps to KUBE-EXTERNAL-SERVICES: error appending rule: exit status 1: iptables: No chain/target/match by that name.
2019-07-18T18:32:49.7576353Z stderr F E0718 18:32:49.756511       1 proxier.go:714] Failed to ensure that filter chain INPUT jumps to KUBE-EXTERNAL-SERVICES: error appending rule: exit status 1: iptables: No chain/target/match by that name.

```

**What you expected to happen**:

Node should go into ready state, no errors with CNI

**How to reproduce it (as minimally and precisely as possible)**:

`kind create cluster`
`kubectl get node` - will show kind-control-plane as `NotReady`

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.4.0
- Kubernetes version: (use `kubectl version`): v1.15.0
- Docker version: (use `docker info`): 18.09.6
- OS (e.g. from `/etc/os-release`): "Ubuntu 18.04.2 LTS"  under WSL2
- `uname -a`: Linux DESKTOP-7B0VHAB 4.19.43-microsoft-standard #1 SMP Sat Jun 1 16:36:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by PatrickLang** [comment]
oops dupe of #707
/close

**Comment by BenTheElder** [comment]
Yeah, I'm not sure what to do here. We should make kind not fail in this case probably, but this also affects the IP masq agent.

**Comment by aojea** [comment]
I think that is not only the CNI that will fail, kube-proxy is using iptables too
