### ISSUE TITLE
kindnet panics sometimes on ip6tables-restore and iptables-restore

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#944]
**What happened**:

> 2019-10-12T07:48:20.101394314Z stderr F panic: exit status 1 (ip6tables-restore: line 5 failed
> 2019-10-12T07:48:20.101469169Z stderr F )
> 2019-10-12T07:48:20.101476874Z stderr F 
> 2019-10-12T07:48:20.101483906Z stderr F goroutine 22 [running]:
> 2019-10-12T07:48:20.101491264Z stderr F main.main.func1(0xc000243400)
> 2019-10-12T07:48:20.101498175Z stderr F 	/src/main.go:76 +0x67
> 2019-10-12T07:48:20.101504071Z stderr F created by main.main
> 2019-10-12T07:48:20.101509918Z stderr F 	/src/main.go:73 +0x318
> 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/943/pull-kind-conformance-parallel-ipv6/1182919191846457348/artifacts/logs/kind-worker2/pods/kube-system_kindnet-g248m_e664ffe1-a561-4897-8952-487625db3a1d/kindnet-cni/2.log

**Anything else we need to know?**:

Ben mentioned several times that ipv6 tests are flakier than the ipv4 ones. This can be some of the reasons

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by aojea** [comment]
The lines are exactly the same as the ones created 1 minute before, however, this time fail to commit them

```
2019-10-12T07:48:19.495239187Z stdout F Handling iptables: *nat
2019-10-12T07:47:17.992170687Z stdout F Handling iptables: *nat

2019-10-12T07:48:19.495245083Z stdout F :KIND-MASQ-AGENT - [0:0]
2019-10-12T07:47:17.992178034Z stdout F :KIND-MASQ-AGENT - [0:0]

2019-10-12T07:48:19.495251727Z stdout F -A KIND-MASQ-AGENT -m comment --comment "kind-masq-agent: local traffic is not subject to MASQUERADE" -d fd00:10:244::/64 -j RETURN
2019-10-12T07:47:17.99218499dZ stdout F -A KIND-MASQ-AGENT -m comment --comment "kind-masq-agent: local traffic is not subject to MASQUERADE" -d fd00:10:244::/64 -j RETURN

2019-10-12T07:48:19.495258164Z stdout F -A KIND-MASQ-AGENT -m comment --comment "ip-masq-agent: outbound traffic is subject to MASQUERADE (must be last in chain)" -j MASQUERADE
2019-10-12T07:47:17.992191935Z stdout F -A KIND-MASQ-AGENT -m comment --comment "ip-masq-agent: outbound traffic is subject to MASQUERADE (must be last in chain)" -j MASQUERADE

2019-10-12T07:48:19.495264866Z stdout F COMMIT
2019-10-12T07:47:17.992199582Z stdout F COMMIT
```

maybe a bug in iptables or in the kernel of that instance?

**Comment by aojea** [comment]
it's happening with ipv4 too

```
2019-10-12T14:57:21.271757282Z stdout F Handling iptables: *nat
2019-10-12T14:57:21.27176359Z stdout F :KIND-MASQ-AGENT - [0:0]
2019-10-12T14:57:21.271771294Z stdout F -A KIND-MASQ-AGENT -m comment --comment "kind-masq-agent: local traffic is not subject to MASQUERADE" -d 10.244.0.0/16 -j RETURN
2019-10-12T14:57:21.271782355Z stdout F -A KIND-MASQ-AGENT -m comment --comment "ip-masq-agent: outbound traffic is subject to MASQUERADE (must be last in chain)" -j MASQUERADE
2019-10-12T14:57:21.271789589Z stdout F COMMIT
2019-10-12T14:57:21.271795936Z stdout F 
2019-10-12T14:57:21.46632461Z stderr F panic: exit status 1 (iptables-restore: line 5 failed
2019-10-12T14:57:21.466437133Z stderr F )
2019-10-12T14:57:21.46644897Z stderr F 
2019-10-12T14:57:21.466458578Z stderr F goroutine 18 [running]:
2019-10-12T14:57:21.466466839Z stderr F main.main.func1(0xc0002ac040)
2019-10-12T14:57:21.466475613Z stderr F 	/src/main.go:76 +0x67
2019-10-12T14:57:21.466482544Z stderr F created by main.main
2019-10-12T14:57:21.466489646Z stderr F 	/src/main.go:73 +0x318
```

**Comment by aojea** [comment]
Confirmed that is causing flakiness, these tests failed because of timeouts are having those panics

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-kind-ipv6/1182272891635372032

I'm starting to think that it can be a race condition or a conflict with others (kube-proxy, kubelet, ..)

**Comment by aojea** [comment]
reproduced running the e2e test suite and this inside kindnet

```
# while true; do ip6tables-restore < test.tables; echo restore; sleep 2; done
```
test.tables contains a snapshot of the tables.

I think that the first step is something that Ben already mentioned several times, we are panicing too much in  kind, this iptables error is clearly recoverable since we run it in a loop

**Comment by aojea** [comment]
some logs that seems related in the kube-proxy logs

```
2019-10-11T06:19:12.500688715Z stderr F I1011 06:19:12.500363       1 shared_informer.go:204] Caches are synced for service config 
2019-10-11T06:22:27.231651477Z stderr F E1011 06:22:27.231396       1 proxier.go:732] Failed to ensure that filter chain INPUT jumps to KUBE-EXTERNAL-SERVICES: error checking rule: exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-11T06:22:38.1196209Z stderr F E1011 06:22:38.119140       1 proxier.go:732] Failed to ensure that filter chain FORWARD jumps to KUBE-SERVICES: error checking rule: exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-11T06:24:00.823213842Z stderr F I1011 06:24:00.822985       1 trace.go:116] Trace[409041330]: "iptables restore" (started: 2019-10-11 06:23:58.822429637 +0000 UTC m=+286.637350522) (total time: 2.000481866s):
2019-10-11T06:24:00.823278511Z stderr F Trace[409041330]: [2.000481866s] [2.000481866s] END
2019-10-11T06:24:00.823289511Z stderr F E1011 06:24:00.823099       1 proxier.go:1429] Failed to execute iptables-restore: failed to acquire new iptables lock: timed out waiting for the condition
2019-10-11T06:24:58.727938357Z stderr F E1011 06:24:58.727621       1 proxier.go:724] Failed to ensure that filter chain KUBE-SERVICES exists: error creating chain "KUBE-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
````

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/83711/pull-kubernetes-conformance-kind-ipv6/1182537871349780480/artifacts/logs/kind-worker2/containers/kube-proxy-bxz9q_kube-system_kube-proxy-ccd5328453516a1097b4abef9b00764ea0b67d51c7c135cf3e2f4b6d56f1de5d.log

**Comment by aojea** [comment]
hopefully this will reduce the flakiness https://testgrid.k8s.io/conformance-kind#kind%20(IPv6),%20master%20(dev)%20%5Bnon-serial%5D&width=5
